/**
 * Image assets generated by MiniMax AI.
 *
 * Usage:
 *   import { Illustrations } from '../assets/illustrations';
 *   <Image source={Illustrations.emptyPlate} />
 *
 * To regenerate: `mmx image generate --prompt "..." --out-dir assets/generated/healthlens-v2`
 * Then drop the PNG into both:
 *   - src/assets/illustrations/   (for JS bundling)
 *   - ios/HealthLens/Images.xcassets/<name>.imageset/  (for Xcode catalog)
 */

export const Illustrations = {
  emptyPlate: require('./illustrations/empty_plate.png'),
  emptyHistory: require('./illustrations/empty_history.png'),
  aiScanning: require('./illustrations/ai_scanning.png'),
  gradeAPlus: require('./illustrations/grade_a_plus.png'),
  waterTracking: require('./illustrations/water_tracking.png'),
  goalHypertension: require('./illustrations/goal_hypertension.png'),
  goalDiabetes: require('./illustrations/goal_diabetes.png'),
  goalGutHealth: require('./illustrations/goal_gut_health.png'),
  goalWeight: require('./illustrations/goal_weight.png'),
  splashLogo: require('./illustrations/splash.png'),
  appIconGrade: require('./illustrations/image_001.png'),
} as const;

export type IllustrationKey = keyof typeof Illustrations;
